gui:
  screenMode: half
  skipAmendWarning: true
  skipStashWarning: true
  skipNoStagedFilesWarning: true
  showNumstatInFilesView: true
  showRandomTip: false
  showDivergenceFromBaseBranch: arrowAndNumber
  nerdFontsVersion: "3"
  filterMode: fuzzy
  border: hidden
  animateExplosion: true
  theme:
    activeBorderColor:
      - "#be95ff"
      - bold
    inactiveBorderColor:
      - "#525252"
    searchingActiveBorderColor:
      - "#3ddbd9"
      - bold
    optionsTextColor:
      - "#78a9ff"
    selectedLineBgColor:
      - "#393939"
    inactiveViewSelectedLineBgColor:
      - "#262626"
    cherryPickedCommitFgColor:
      - "#ff7eb6"
    cherryPickedCommitBgColor:
      - "#262626"
    markedBaseCommitFgColor:
      - "#161616"
    markedBaseCommitBgColor:
      - "#be95ff"
    unstagedChangesColor:
      - "#ee5396"
    defaultFgColor:
      - "#f2f4f8"
git:
  pagers:
    - pager: delta --paging=never
      colorArg: always
  autoForwardBranches: allBranches
  diffContextSize: 5
  parseEmoji: true
os:
  editPreset: nvim
customCommands:
  - key: "c"
    context: "files"
    description: "convco commit"
    command: "convco commit"
    output: terminal
  - key: "C"
    context: "files"
    description: "convco commit --amend"
    command: "convco commit --amend"
    output: terminal
